<a href="https://colab.research.google.com/github/19PA1A0275/AI-LAB/blob/master/Experiment_1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 EXPERIMENT-1

1) NUMPY

I) Different ways to create numpy arrays.

In [1]:
import numpy as np
a = np.array([2,6,9])
print (a)

[2 6 9]


In [2]:
a = np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


ii) Add, Remove , modify elements in an array.

In [3]:
newArray = np.append(a,[44,36,48])
print(newArray)

[ 1  2  3  4 44 36 48]


In [6]:
import numpy as np
l=np.array([4,6,9,3,7])
l=np.delete(l,4)
print(l)

[4 6 9 3]


In [7]:
b=np.array([9,6,4,1,8,5])
b[b<2]=-1
print(b)

[ 9  6  4 -1  8  5]


 iii) Arithmetic operations on numpy array.

In [13]:
import numpy as np
v=np.random.random((8,8))
n=np.random.random((8,8))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.11055604 0.89090683 1.08593657 1.42362767 0.88510058 0.70614461
  1.10359653 1.00542923]
 [0.52677093 1.0853333  1.44824286 1.1471786  0.34774473 0.9737489
  1.09046038 0.44126114]
 [0.50670264 1.21577261 0.64370369 1.01194024 1.68129716 1.32233132
  0.53495433 1.61864434]
 [0.98156832 1.54366536 1.19204317 1.08699759 1.70352655 1.24695007
  1.06810044 1.61270597]
 [1.54334312 0.80644319 0.74218005 1.12460615 1.65213078 1.24967119
  0.92781567 1.03680834]
 [0.71264375 1.81144121 0.62057639 1.34120816 0.61606774 1.1774068
  0.49482648 0.44894124]
 [0.93156726 1.29688958 1.3481092  0.91474959 0.6353618  1.02880661
  1.01171348 0.59395682]
 [1.25406633 1.16223703 0.23737996 1.16943004 0.3797014  0.26006899
  0.59873201 0.69875853]]
[[ 0.09285305  0.77899204  0.43865688  0.29545307 -0.07118737 -0.4589818
   0.76452139 -0.78843314]
 [-0.13709582 -0.69027035 -0.2272434  -0.28512215 -0.27288083 -0.78804875
   0.81360393 -0.439186  ]
 [ 0.0649379  -0.45353286  0.37910499 -0.90799603  0.223

 iv) Slicing and iterating of numpy arrays.

Slicing

In [10]:
import numpy as np
arr=np.array([4,5,6,8,9,7])
print(arr[2:6])

[6 8 9 7]


 Iterating

In [11]:
for i in arr: 
  print(i)

4
5
6
8
9
7


 V) Matrix operations on numpy arrays.

In [12]:
 
import numpy as np
v=np.array([[5,9],[4,3]])
i=np.array([[2,16],[1,12]])
print(np.add(v,i))
print(np.subtract(v,i))
print(np.divide(v,i))

[[ 7 25]
 [ 5 15]]
[[ 3 -7]
 [ 3 -9]]
[[2.5    0.5625]
 [4.     0.25  ]]
